version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/springboottest-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - application_start.sh
    - application_stop.sh
  discard-paths: yes